//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunExplorerBot.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FunEvent
    {
        public int Id { get; set; }
        public string EventName { get; set; }
        public string Location { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> Duration { get; set; }
        public string Memo { get; set; }
    }
}
